/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Admin (void);
GtkWidget* create_auth (void);
GtkWidget* create_inscription (void);
GtkWidget* create_Gestion_ouvrier (void);
GtkWidget* create_Gestion_equipment (void);
GtkWidget* create_Gestion__troupeaux_ (void);
GtkWidget* create_Gestion_client (void);
GtkWidget* create_Gestion_capteur (void);
GtkWidget* create_Gestion_calendrier (void);
GtkWidget* create_espace_reclamation_ (void);
GtkWidget* create_espace_responsable_ (void);
GtkWidget* create_window1 (void);
